#!/usr/bin/env python3
"""Check whether docs/screenshots/*.png are true screenshots, real-ish mocks, or placeholder copies.

This repo includes SVG placeholders and a generated PNG set under:
  docs/screenshots/png/*.png

The landing page references docs/screenshots/*.png.
During development, those files may be:
  - exact placeholder copies (bad)
  - "real-ish" mocks generated by scripts/generate_realish_screenshots.py (ok for docs, not ideal for listings)
  - true screenshots captured from a real Google Sheet (preferred)

Detection:
  1) PLACEHOLDER: sha256(docs/screenshots/<name>.png) == sha256(docs/screenshots/png/<name>.png)
  2) REALISH: sha256(docs/screenshots/<name>.png) matches docs/screenshots/realish-hashes.json

Exit codes:
  0: ok (or non-failing findings)
  2: placeholders found and --fail-on-placeholders
  3: missing files
  4: real-ish screenshots found and --fail-on-realish
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOP_DIR = ROOT / "docs" / "screenshots"
PLACEHOLDER_DIR = TOP_DIR / "png"
REALISH_HASHES_PATH = TOP_DIR / "realish-hashes.json"

NAMES = [
    "01-menu.png",
    "02-requests-pending.png",
    "03-approved-row.png",
    "04-audit-entry.png",
    "05-reapproval-required.png",
    "06-help-sidebar.png",
]


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_realish_hashes() -> dict[str, str]:
    if not REALISH_HASHES_PATH.exists():
        return {}
    try:
        payload = json.loads(REALISH_HASHES_PATH.read_text(encoding="utf-8"))
        files = payload.get("files")
        if isinstance(files, dict):
            out: dict[str, str] = {}
            for k, v in files.items():
                if isinstance(k, str) and isinstance(v, str) and len(v) >= 32:
                    out[k] = v
            return out
    except Exception:
        return {}
    return {}


def sips_px(p: Path) -> tuple[int | None, int | None]:
    """Best-effort pixel dimensions (macOS only). Returns (w, h) or (None, None)."""
    if shutil.which("sips") is None:
        return (None, None)
    try:
        proc = subprocess.run(
            ["sips", "-g", "pixelWidth", "-g", "pixelHeight", str(p)],
            check=False,
            capture_output=True,
            text=True,
        )
        out = (proc.stdout or "") + "\n" + (proc.stderr or "")
        w: int | None = None
        h: int | None = None
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("pixelWidth:"):
                try:
                    w = int(line.split(":", 1)[1].strip())
                except Exception:
                    pass
            if line.startswith("pixelHeight:"):
                try:
                    h = int(line.split(":", 1)[1].strip())
                except Exception:
                    pass
        return (w, h)
    except Exception:
        return (None, None)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--fail-on-placeholders",
        action="store_true",
        help="Exit non-zero if any top-level screenshot PNG is still a placeholder copy.",
    )
    ap.add_argument(
        "--fail-on-realish",
        action="store_true",
        help="Exit non-zero if any top-level screenshot PNG is still a 'real-ish' mock (generated).",
    )
    ap.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON (still prints nothing else).",
    )
    ap.add_argument(
        "--show-info",
        action="store_true",
        help="Print file size + best-effort pixel dimensions for each screenshot (uses macOS `sips` if available).",
    )
    args = ap.parse_args()

    missing: list[str] = []
    placeholders: list[str] = []
    realish: list[str] = []

    info: dict[str, dict[str, int | None]] = {}

    realish_hashes = load_realish_hashes()

    for name in NAMES:
        top = TOP_DIR / name
        ph = PLACEHOLDER_DIR / name

        if not top.exists():
            missing.append(str(top.relative_to(ROOT)))
            continue
        if not ph.exists():
            missing.append(str(ph.relative_to(ROOT)))
            continue

        try:
            top_h = sha256(top)
            if top_h == sha256(ph):
                placeholders.append(name)
            elif realish_hashes.get(name) == top_h:
                realish.append(name)

            w, h = sips_px(top)
            try:
                size = top.stat().st_size
            except Exception:
                size = None
            info[name] = {"bytes": size, "width": w, "height": h}
        except OSError:
            missing.append(name)

    if args.json:
        payload = {
            "ok": not missing
            and not placeholders
            and (not args.fail_on_realish or not realish),
            "missing": missing,
            "placeholders": [f"docs/screenshots/{n}" for n in placeholders],
            "realish": [f"docs/screenshots/{n}" for n in realish],
            "info": {k: {"bytes": v.get("bytes"), "width": v.get("width"), "height": v.get("height")} for k, v in info.items()},
            "infoNote": "Pixel dimensions are best-effort (macOS uses `sips`).",
        }
        print(json.dumps(payload, indent=2))
        if missing:
            return 3
        if placeholders and args.fail_on_placeholders:
            return 2
        if realish and args.fail_on_realish:
            return 4
        return 0

    if args.show_info and not missing:
        print("[screenshots] INFO (size + pixels):")
        for name in NAMES:
            v = info.get(name) or {}
            b = v.get("bytes")
            w = v.get("width")
            h = v.get("height")
            px = f"{w}×{h}" if (w and h) else "(px unknown)"
            bs = f"{b}" if b is not None else "(bytes unknown)"
            print(f"  - {name}: {bs} bytes, {px}")
        print("")

    if missing:
        print("[screenshots] MISSING files:")
        for m in missing:
            print(f"  - {m}")
        return 3

    if placeholders:
        print("[screenshots] PLACEHOLDER copies detected (top-level PNG matches placeholder PNG):")
        for n in placeholders:
            print(f"  - docs/screenshots/{n}")

        print("\nNext steps:")
        print("  - Quick cheatsheet: docs/screenshots/CAPTURE-CHEATSHEET.md")
        print("  - Full guide: REAL_SCREENSHOTS_GUIDE.md")
        print("  - Helper installer: python3 scripts/install_real_screenshots.py --from ~/Desktop")

        if args.fail_on_placeholders:
            return 2
        return 0

    if realish:
        print("[screenshots] WARNING — 'real-ish' generated screenshots detected (not true Google Sheets captures):")
        for n in realish:
            print(f"  - docs/screenshots/{n}")

        print("\nNext steps (preferred):")
        print("  - Capture true screenshots: REAL_SCREENSHOTS_GUIDE.md")
        print("  - Then re-check: python3 scripts/check_screenshots.py --fail-on-placeholders --fail-on-realish")

        if args.fail_on_realish:
            return 4
        return 0

    print("[screenshots] OK — screenshots are not placeholders (and do not match known real-ish mocks).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
